### ISSUE TITLE
BUG: Cannot create Profile file in folder that does not exist.

### ISSUE THREAD

**Issue by robinschiro** [GeorgeSchiro/GoPcBackup#14]
https://github.com/GeorgeSchiro/GoPcBackup/blob/b8d1a6e32a5606a36789750c48033b0503ea1f71/GoPcBackupApp/Resources/tvToolbox/tvProfile.cs#L3107

When Profile file creation is attempted, creation fails if the path contains a folder than does not exist.

**Comment by robinschiro** [comment]
@GeorgeSchiro Hopefully this generates an email.

**Comment by GeorgeSchiro** [comment]
This is fixed in the current release.
